{% set version = "0.15.1" %}

package:
  name: jupyterlab
  version: {{ version }}

source:
    fn: jupyterlab-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/j/jupyterlab/jupyterlab-{{ version }}.tar.gz
    sha256: 8e5572d831b7192cd1be23809a3006105d9c6075c7229c637112a64351c11240

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - jupyter-lab = jupyterlab.labapp:main
    - jupyter-labextension = jupyterlab.labextensions:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - notebook >=4.2

test:
  imports:
    - jupyterlab

about:
  home: https://github.com/jupyter/jupyterlab
  license: BSD 3-Clause
  summary: A pre-alpha version of a computational environment for Jupyter.

extra:
  recipe-maintainers:
    - jasongrout
    - blink1073
