{% set version = "3.6.4" %}

package:
  name: jupyterlab
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyterlab/jupyterlab-{{ version }}.tar.gz
  sha256: 862fb4a06c759a9b0a12de6bf434a8681a42e52fff0593c120e3fbad6847889f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - jlpm = jupyterlab.jlpmapp:main
    - jupyter-lab = jupyterlab.labapp:main
    - jupyter-labextension = jupyterlab.labextensions:main
    - jupyter-labhub = jupyterlab.labhubapp:main

requirements:
  host:
    - jupyter-packaging >=0.9,<2
    - packaging
    - pip
    - python >=3.7
  run:
    - ipython
    - jinja2 >=2.1
    - jupyter_core
    - jupyter_server >=1.16.0,<3
    - jupyter_server_ydoc >=0.8.0,<0.9.0
    - jupyter_ydoc >=0.2.3,<0.3
    - jupyterlab_server >=2.19,<3
    - nbclassic
    - notebook <7
    - packaging
    - python >=3.7
    - tomli
    - tornado >=6.1.0

test:
  requires:
    - nodejs >=16.*,!=17.*,<19
    - pip
    - m2-grep  # [win]
  imports:
    - jupyterlab
  commands:
    - pip check
    - jupyter lab --version
    - jlpm --version
    - jlpm versions
    - jupyter labextension list
    - jupyter lab licenses
    - jupyter lab path
    - jupyter server extension list
    - jupyter serverextension list
    - jupyter server extension list 1>server_extensions 2>&1
    - cat server_extensions | grep "jupyterlab.*{{ version.replace(".", "\\.") }}.*OK"
    - jupyter serverextension list 1>serverextensions 2>&1
    - cat serverextensions | grep "jupyterlab.*{{ version.replace(".", "\\.") }}.*OK"
    - jupyter lab build --dev-build=False --minimize=False
    - jupyter lab clean

about:
  home: https://github.com/jupyterlab/jupyterlab
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - jupyterlab/static/third-party-licenses.json
  summary: >
    An extensible environment for interactive and reproducible computing, based on the Jupyter Notebook and Architecture.
  doc_url: https://jupyterlab.readthedocs.io
  dev_url: https://github.com/jupyterlab/jupyterlab
  description: >
    JupyterLab is the next-generation user interface for Project Jupyter. It offers all the familiar building blocks of the classic Jupyter Notebook (notebook, terminal, text editor, file browser, rich outputs, etc.) in a flexible and powerful user inteface. Eventually, JupyterLab will replace the classic Jupyter Notebook.
    JupyterLab can be extended using extensions that are npm packages and use our public APIs. You can search for the GitHub topic or npm keyword `jupyterlab-extension` to find extensions. To learn more about extensions, see our user documentation. JupyterLab is suitable for general usage. For JupyterLab extension developers,
    the extension APIs will continue to evolve.
extra:
  recipe-maintainers:
    - afshin
    - blink1073
    - bollwyvl
    - ellisonbg
    - fcollonval
    - ian-r-rose
    - jasongrout
    - jochym
    - jtpio
