{% set version = "3.0.0rc14" %}
{% set sha256 = "053b7c6be74bc7cbf2736c633459a5848d3e93e6d7ca919cd2f903599590320f" %}


package:
  name: jupyterlab
  version: {{ version }}

source:
  fn: jupyterlab-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/j/jupyterlab/jupyterlab-{{ version }}.tar.gz
  sha256: {{ sha256 }}
build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --install-option="--skip-npm" . -vv
  entry_points:
    - jupyter-lab = jupyterlab.labapp:main
    - jupyter-labextension = jupyterlab.labextensions:main
    - jupyter-labhub = jupyterlab.labhubapp:main
    - jlpm = jupyterlab.jlpmapp:main

requirements:
  host:
    - python >=3.6
    - pip
    - nodejs >=12
    - jupyter-packaging
    - packaging
  run:
    - python >=3.6
    - jupyter_core
    - jupyterlab_server >=2.0.0rc1,<3.0.0
    - jupyter_server >=1.0.1,<2.0.0
    - nbclassic >=0.2.0,<0.3.0
    - tornado >=6.1
    - jinja2 >=2.10
    - packaging

test:
  requires:
    - nodejs >=12
  imports:
    - jupyterlab
  commands:
    - jupyter lab --version
    - jlpm --version
    - jlpm versions
    - jupyter labextension list
    - jupyter lab path
    - jupyter lab build
    - jupyter lab clean

about:
  home: https://github.com/jupyterlab/jupyterlab
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: >
    An extensible environment for interactive and reproducible computing, based on the Jupyter Notebook and Architecture.
  doc_url: https://jupyterlab.readthedocs.io
  dev_url: https://github.com/jupyterlab/jupyterlab
  description: >
    JupyterLab is the next-generation user interface for Project Jupyter. It offers all the familiar building blocks of the classic Jupyter Notebook (notebook, terminal,
    text editor, file browser, rich outputs, etc.) in a flexible and powerful user inteface. Eventually, JupyterLab will replace the classic Jupyter Notebook.

    JupyterLab can be extended using extensions that are npm packages and use our public APIs. You can search for the GitHub topic or npm keyword `jupyterlab-extension`
    to find extensions. To learn more about extensions, see our user documentation.

    JupyterLab is suitable for general usage. For JupyterLab extension developers, the extension APIs will continue to evolve.

extra:
  recipe-maintainers:
    - jasongrout
    - blink1073
    - jochym
    - ian-r-rose
    - afshin
    - ellisonbg
    - jtpio
