
{% set version = "1.0.6" %}
{% set sha256 = "905286f2608ff8a5595f9a941d46e7a8ff9c98a3dac6b88794f14a4563d65ced" %}


package:
  name: jupyterlab
  version: {{ version }}

source:
    fn: jupyterlab-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/j/jupyterlab/jupyterlab-{{ version }}.tar.gz
    sha256: {{ sha256 }}
build:
  number: 0
  skip: True  # [py<35]
  script: python -m pip install --no-deps --ignore-installed --install-option="--skip-npm" --verbose .
  entry_points:
    - jupyter-lab = jupyterlab.labapp:main
    - jupyter-labextension = jupyterlab.labextensions:main
    - jupyter-labhub = jupyterlab.labhubapp:main

requirements:
  build:
    - python
    - pip
    - nodejs >=8
  run:
    - python
    - jupyterlab_server >=1.0.0,<2.0.0
    - notebook >=4.3.1
    - tornado !=6.0.0,!=6.0.1,!=6.0.2
test:
  requires:
    - nodejs
  imports:
    - jupyterlab
  commands:
    - jupyter lab --version
    - jlpm --version
    - jlpm versions
    - jupyter labextension list
    - jupyter lab path
    - jupyter lab build
    - jupyter lab clean

about:
  home: https://github.com/jupyterlab/jupyterlab
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: >
    An extensible environment for interactive and reproducible computing, based
    on the Jupyter Notebook and Architecture.
  doc_url: https://jupyterlab.readthedocs.io
  dev_url: https://github.com/jupyterlab/jupyterlab
  description: >
    JupyterLab is the next-generation user interface for Project Jupyter. It
    offers all the familiar building blocks of the classic Jupyter Notebook
    (notebook, terminal, text editor, file browser, rich outputs, etc.) in a
    flexible and powerful user inteface. Eventually, JupyterLab will replace
    the classic Jupyter Notebook.

    JupyterLab can be extended using extensions that are npm packages and use
    our public APIs. You can search for the GitHub topic or npm keyword
    `jupyterlab-extension` to find extensions. To learn more about extensions,
    see our user documentation.

    JupyterLab is suitable for general usage. For JupyterLab extension
    developers, the extension APIs will continue to evolve.

extra:
  recipe-maintainers:
    - jasongrout
    - blink1073
    - jochym
    - ian-r-rose
    - afshin
    - ellisonbg
