{% set version = "4.5.0b1" %}

package:
  name: jupyterlab
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyterlab/jupyterlab-{{ version }}.tar.gz
  sha256: 98345a3d7e57b216b58e15b89f3a676f664a6bc738f87949ee3cca04c06243cf

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  entry_points:
    - jupyter-lab = jupyterlab.labapp:main
    - jupyter-labextension = jupyterlab.labextensions:main
    - jupyter-labhub = jupyterlab.labhubapp:main
    - jlpm = jupyterlab.jlpmapp:main

requirements:
  host:
    - python-build
    - hatch-jupyter-builder >=0.3.2
    - hatchling >=1.21.1
    - pip
    - python {{ python_min }}
  run:
    - async-lru >=1.0.0
    - httpx >=0.25.0,<1
    - ipykernel >=6.5.0,!=6.30.0
    - jinja2 >=3.0.3
    - jupyter_core
    - jupyter_server >=2.4.0,<3
    - jupyter-lsp >=2.0.0
    - jupyterlab_server >=2.27.1,<3
    - notebook-shim >=0.2
    - packaging
    - python >={{ python_min }}
    - setuptools >=41.1.0
    - tomli >=1.2.2
    - tornado >=6.2.0
    - traitlets

test:
  requires:
    - nodejs >=22,<23
    - pip
    - python {{ python_min }}
  imports:
    - jupyterlab
  commands:
    - pip check
    - jupyter lab --version
    - jlpm --version
    # TODO: figure out a handy command for yarn 3.4+ that emulates the previous version lister
    # - jlpm versions
    - jupyter labextension list
    - jupyter lab licenses
    - jupyter lab path
    - jupyter server extension list
    - jupyter server extension list 2>&1 | python -c "import sys, re; ok = re.findall(r'jupyterlab.*{{ version.replace(".", "\\.") }}.*OK', sys.stdin.read()); print(ok); assert ok, 'server extension is not ok'"
    - jupyter lab build --dev-build=False --minimize=False
    - jupyter lab clean

app:
  entry: jupyter lab
  icon: icon.png
  summary: JupyterLab {{ version }}
  type: desk

about:
  home: https://github.com/jupyterlab/jupyterlab
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - jupyterlab/static/third-party-licenses.json
  summary: >
    An extensible environment for interactive and reproducible computing, based on the Jupyter Notebook and Architecture.
  doc_url: https://jupyterlab.readthedocs.io
  dev_url: https://github.com/jupyterlab/jupyterlab
  description: >
    JupyterLab is the next-generation user interface for Project Jupyter. It offers all the familiar building blocks of the classic Jupyter Notebook (notebook, terminal, text editor, file browser, rich outputs, etc.) in a flexible and powerful user inteface. Eventually, JupyterLab will replace the classic Jupyter Notebook.

    JupyterLab can be extended using extensions that are npm packages and use our public APIs. You can search for the GitHub topic or npm keyword `jupyterlab-extension` to find extensions. To learn more about extensions, see our user documentation.

    JupyterLab is suitable for general usage. For JupyterLab extension developers, the extension APIs will continue to evolve.

extra:
  recipe-maintainers:
    - krassowski
    - afshin
    - blink1073
    - bollwyvl
    - ellisonbg
    - fcollonval
    - ian-r-rose
    - jasongrout
    - jochym
    - jtpio
