{% set version = "3.0.9" %}

package:
  name: jupyterlab
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyterlab/jupyterlab-{{ version }}.tar.gz
  sha256: 70aa808a1adc06e35701500a0b1cd2f472ad55b8d890153cb8bdfbd30b279646
build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --install-option="--skip-npm" . -vv
  entry_points:
    - jupyter-lab = jupyterlab.labapp:main
    - jupyter-labextension = jupyterlab.labextensions:main
    - jupyter-labhub = jupyterlab.labhubapp:main
    - jlpm = jupyterlab.jlpmapp:main

requirements:
  host:
    - jupyter-packaging >=0.7.3,<0.8.0
    - nodejs >=12,!=13,!=15,!=17
    - packaging
    - pip
    - python >=3.6
    - wheel
  run:
    - ipython
    - jinja2 >=2.10
    - jupyter_core
    - jupyter_packaging >=0.7.3,<0.8.0
    - jupyter_server >=1.4,<2
    - jupyterlab_server >=2.3,<3
    - nbclassic >=0.2,<1
    - packaging
    - python >=3.6
    - tornado >=6.1
test:
  requires:
    - nodejs >=12
    - pip
    - m2-grep  # [win]
  imports:
    - jupyterlab
  commands:
    - pip check
    - jupyter lab --version
    - jlpm --version
    - jlpm versions
    - jupyter labextension list
    - jupyter lab path
    - jupyter server extension list
    - jupyter serverextension list
    - jupyter server extension list 1>server_extensions 2>&1
    - cat server_extensions | grep "jupyterlab.*{{ version.replace(".", "\\.") }}.*OK"
    - jupyter serverextension list 1>serverextensions 2>&1
    - cat serverextensions | grep "jupyterlab.*{{ version.replace(".", "\\.") }}.*OK"
    - jupyter lab build
    - jupyter lab clean

about:
  home: https://github.com/jupyterlab/jupyterlab
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: >
    An extensible environment for interactive and reproducible computing, based on the Jupyter Notebook and Architecture.
  doc_url: https://jupyterlab.readthedocs.io
  dev_url: https://github.com/jupyterlab/jupyterlab
  description: >
    JupyterLab is the next-generation user interface for Project Jupyter. It offers all the familiar building blocks of the classic Jupyter Notebook (notebook, terminal, text editor, file browser, rich outputs, etc.) in a flexible and powerful user inteface. Eventually, JupyterLab will replace the classic Jupyter Notebook.

    JupyterLab can be extended using extensions that are npm packages and use our public APIs. You can search for the GitHub topic or npm keyword `jupyterlab-extension` to find extensions. To learn more about extensions, see our user documentation.

    JupyterLab is suitable for general usage. For JupyterLab extension developers, the extension APIs will continue to evolve.

extra:
  recipe-maintainers:
    - jasongrout
    - blink1073
    - jochym
    - ian-r-rose
    - afshin
    - ellisonbg
    - jtpio
    - bollwyvl
