{% set version = "4.0.10" %}

package:
  name: jupyterlab
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyterlab/jupyterlab-{{ version }}.tar.gz
  sha256: 46177eb8ede70dc73be922ac99f8ef943bdc2dfbc6a31b353c4bde848a35dee1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - jupyter-lab = jupyterlab.labapp:main
    - jupyter-labextension = jupyterlab.labextensions:main
    - jupyter-labhub = jupyterlab.labhubapp:main
    - jlpm = jupyterlab.jlpmapp:main

requirements:
  host:
    - python-build
    - hatch-jupyter-builder >=0.3.2
    - hatchling >=1.5.0
    - pip
    - python >=3.8
  run:
    - async-lru >=1.0.0
    - importlib_metadata >=4.8.3
    - importlib_resources >=1.4
    - ipykernel
    - jinja2 >=3.0.3
    - jupyter_core
    - jupyter-lsp >=2.0.0
    - jupyter_server >=2.4.0,<3
    - jupyterlab_server >=2.19.0,<3
    - notebook-shim >=0.2
    - packaging
    - python >=3.8
    - traitlets
    - tornado >=6.2.0
    - tomli

test:
  requires:
    - nodejs >=18,<19
    - pip
    - m2-grep  # [win]
  imports:
    - jupyterlab
  commands:
    - pip check
    - jupyter lab --version
    - jlpm --version
    # TODO: figure out a handy command for yarn 3.4+ that emulates the previous version lister
    # - jlpm versions
    - jupyter labextension list
    - jupyter lab licenses
    - jupyter lab path
    - jupyter server extension list
    - jupyter server extension list 1>server_extensions 2>&1
    - grep -iE "jupyterlab.*{{ version.replace(".", "\\.") }}.*OK" server_extensions
    - jupyter lab build --dev-build=False --minimize=False
    - jupyter lab clean

about:
  home: https://github.com/jupyterlab/jupyterlab
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - jupyterlab/static/third-party-licenses.json
  summary: >
    An extensible environment for interactive and reproducible computing, based on the Jupyter Notebook and Architecture.
  doc_url: https://jupyterlab.readthedocs.io
  dev_url: https://github.com/jupyterlab/jupyterlab
  description: >
    JupyterLab is the next-generation user interface for Project Jupyter. It offers all the familiar building blocks of the classic Jupyter Notebook (notebook, terminal, text editor, file browser, rich outputs, etc.) in a flexible and powerful user inteface. Eventually, JupyterLab will replace the classic Jupyter Notebook.

    JupyterLab can be extended using extensions that are npm packages and use our public APIs. You can search for the GitHub topic or npm keyword `jupyterlab-extension` to find extensions. To learn more about extensions, see our user documentation.

    JupyterLab is suitable for general usage. For JupyterLab extension developers, the extension APIs will continue to evolve.

extra:
  recipe-maintainers:
    - afshin
    - blink1073
    - bollwyvl
    - ellisonbg
    - fcollonval
    - ian-r-rose
    - jasongrout
    - jochym
    - jtpio
