# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 4.4.0a3

package:
  name: jupyterlab
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyterlab/jupyterlab-${{ version }}.tar.gz
  sha256: 3658b13401240f92e164da8016b0bbb403045a69013e5ea79f62288bb0f6dbba

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - jupyter-lab = jupyterlab.labapp:main
      - jupyter-labextension = jupyterlab.labextensions:main
      - jupyter-labhub = jupyterlab.labhubapp:main
      - jlpm = jupyterlab.jlpmapp:main

requirements:
  host:
    - hatch-jupyter-builder >=0.3.2
    - hatchling >=1.21.1
    - pip
    - python ${{ python_min }}.*
    - python-build
  run:
    - async-lru >=1.0.0
    - httpx >=0.25.0
    - importlib-metadata >=4.8.3
    - ipykernel >=6.5.0
    - jinja2 >=3.0.3
    - jupyter_core
    - jupyter_server >=2.4.0,<3
    - jupyter-lsp >=2.0.0
    - jupyterlab_server >=2.27.1,<3
    - notebook-shim >=0.2
    - packaging
    - python >=${{ python_min }}
    - setuptools >=40.1.0
    - tomli >=1.2.2
    - tornado >=6.2.0
    - traitlets

tests:
  - python:
      pip_check: true
      python_version: ${{ python_min }}.*
      imports:
        - jupyterlab
  - requirements:
      run:
        - nodejs >=22,<23
        - python ${{ python_min }}.*
        - if: win
          then: m2-grep
    script:
      - jupyter lab --version
      - jlpm --version
      - jupyter labextension list
      - jupyter lab licenses
      - jupyter lab path
      - jupyter server extension list
      - jupyter server extension list 1>server_extensions 2>&1
      - grep -iE "jupyterlab.*{{ version | replace(".", "\\.") }}.*OK" server_extensions
      - jupyter lab build --dev-build=False --minimize=False
      - jupyter lab clean

about:
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - jupyterlab/static/third-party-licenses.json
  summary: An extensible environment for interactive and reproducible computing, based on the Jupyter Notebook and Architecture.
  description: >
    JupyterLab is the next-generation user interface for Project Jupyter. It offers all the familiar building blocks of the classic Jupyter Notebook (notebook, terminal, text editor, file browser, rich outputs, etc.) in a flexible and powerful user inteface. Eventually, JupyterLab will replace the classic Jupyter Notebook.

    JupyterLab can be extended using extensions that are npm packages and use our public APIs. You can search for the GitHub topic or npm keyword `jupyterlab-extension` to find extensions. To learn more about extensions, see our user documentation.

    JupyterLab is suitable for general usage. For JupyterLab extension developers, the extension APIs will continue to evolve.


  homepage: https://github.com/jupyterlab/jupyterlab
  repository: https://github.com/jupyterlab/jupyterlab
  documentation: https://jupyterlab.readthedocs.io

extra:
  recipe-maintainers:
    - krassowski
    - afshin
    - blink1073
    - bollwyvl
    - ellisonbg
    - fcollonval
    - ian-r-rose
    - jasongrout
    - jochym
    - jtpio

# rattler-build doesn't support app icons
# app:
#   entry: jupyter lab
#   icon: icon.png
#   summary: JupyterLab ${{ version }}
#   type: desk
