appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: otVRUHO+u7FBfdq8uQBM+495RW0NzDHNflfZCBrhuD12osSrQewvn/CrqOMUGd36C67A/Vukb30YNMMjqg7fLnXf10fOZ2BTVwSdasIG7+Dz1871+vdjAz/VyP0GD5vv+xL0G2ZnWXoD+roLJOEinitXH+xDU0dbXrucy7v0AwtDyRQt8sEE5fwHP1xlAVEoNyYODw8mZ3w3co4+JEMGxMdM9HFlx5wT2dNP5o93l+U/Vptab6iU+b+FT4zQqLguzSagxQMrcWKuyRYvVFNfM6JpTyD9Q5eN0NB81iY/tz+I0n/xLQTjXX8+T7vTYXg/CVY3ufamPqiie+d66Tj4/QFW4eHwmrIFtvzEzxG3jCh5lON1V1KaHjw9v6oBB3UD7O+L3uMsmGDjyx+V0kVr0zZ5gzRyVH4cwDizkOHA9xQ1JxA0Zfqfbx78I7rmcQ1d8RLGqBHFoCLmv9PjNENzR5VbQYj+yjyiRKtkGJktSOR2gPti3CZaxP+O/t6eBfOtleTFxDfn3kEhyFPUxvAnH1VUcShhW4eZmFIW+t7zOuQMRY1B/ts+fjUiZFkSBFSk6OtL1QWCvxjIZL1hAGFbbQCQHRvQHNoeeZuKBL7yfYquLyAgtUqHicBrDFRRdUPr7+/h/Jl1vKLQuhVHMdo69RbkAv4x3NFZHMvWWgKAvuQ=}
provider:
  win: azure
conda_forge_output_validation: true
