conda_forge_output_validation: true

azure:
  # toggle for storing the conda build_artifacts directory (including the
  # built packages) as an Azure pipeline artifact that can be downloaded
  store_build_artifacts: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
bot:
  inspection: hint-all
# TODO: remove once anaconda-client setttls down
remote_ci_setup:
  - conda-forge-ci-setup=4
  - conda-build>=24.1
  - anaconda-client>=1.13.0=pyh29332c3_1
